import '@/styles/globals.css';

//next imports
import type { Metadata } from 'next';

//fonts imports
import { Inter, Lato } from 'next/font/google';
import { Montserrat } from 'next/font/google';

//providers imports
import { Providers } from '@/providers';

const inter = Inter({ subsets: ['latin'] });
const mont = Montserrat({ subsets: ['latin'], display: 'swap' });
const lato = Lato({
  weight: ['700', '400', '300'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Zen Guilty Concessions',
  description: 'Generated by Zen Trainee',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${mont.className} ${inter.className}  bg-customBack h-screen `}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
